local BeyCatalog = {
	{
		id = "NovaStriker",
		name = "Nova Striker",
		beyType = "Attack",
		color = Color3.fromRGB(80, 140, 255),
		accentColor = Color3.fromRGB(120, 210, 255),
		stats = { Attack = 8, Defense = 4, Speed = 7, Stamina = 5 },
		special = "Nova Meteor Shower",
		specialId = "NovaMeteorShower",
		desc = "Attack-Typ: Multi-Hit Meteor-Rush aus der Luft.",
		modelRef = {
			sketchfabId = "6bd1a9f1864a46dba4632307ce6c2660",
			sketchfabUrl = "https://sketchfab.com/models/6bd1a9f1864a46dba4632307ce6c2660",
			referenceName = "Storm Pegasus 105 RF",
			credit = "IcaroAndradeOliveira1",
			studioModelName = "NovaStriker",
		},
	},
	{
		id = "IronShell",
		name = "Iron Shell",
		beyType = "Defense",
		color = Color3.fromRGB(80, 180, 110),
		accentColor = Color3.fromRGB(130, 255, 170),
		stats = { Attack = 4, Defense = 8, Speed = 5, Stamina = 8 },
		special = "Iron Vault Lock",
		specialId = "IronVaultLock",
		desc = "Defense-Typ: Burrow, Schutzmauer und Schockwellen.",
	},
	{
		id = "VoltDash",
		name = "Volt Dash",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 200, 60),
		accentColor = Color3.fromRGB(255, 240, 120),
		stats = { Attack = 6, Defense = 5, Speed = 9, Stamina = 9, SpinDecayMult = 0.65 },
		special = "Volt Sonic Tempest",
		specialId = "VoltSonicTempest",
		desc = "Stamina-Typ: Sonic-Ringe und Orbit-Angriff.",
	},
	{
		id = "ShadowBite",
		name = "Shadow Bite",
		beyType = "Balance",
		color = Color3.fromRGB(140, 80, 220),
		accentColor = Color3.fromRGB(200, 100, 255),
		stats = { Attack = 7, Defense = 6, Speed = 6, Stamina = 6 },
		special = "Shadow Eclipse Fang",
		specialId = "ShadowEclipseFang",
		desc = "Balance-Typ: Dark-Aura, Dive und Venom-Burst.",
	},
	{
		id = "CrimsonFang",
		name = "Crimson Fang",
		beyType = "Attack",
		color = Color3.fromRGB(200, 45, 55),
		accentColor = Color3.fromRGB(255, 90, 70),
		stats = { Attack = 9, Defense = 3, Speed = 8, Stamina = 4 },
		special = "Crimson Rip Tide",
		specialId = "CrimsonRipTide",
		desc = "Attack-Typ: Blutrote Klingen und Meteor-Rush.",
		creatorStore = {
			searchTerms = { "spinning top attack", "bey blade red", "metal fang top" },
			hint = "Toolbox → Creator Store → flaches Top ~3.5 Studs → MeshId in modelAssets.meshId",
		},
	},
	{
		id = "GraniteFort",
		name = "Granite Fort",
		beyType = "Defense",
		color = Color3.fromRGB(110, 105, 95),
		accentColor = Color3.fromRGB(170, 160, 140),
		stats = { Attack = 3, Defense = 9, Speed = 4, Stamina = 9 },
		special = "Granite Bastion",
		specialId = "GraniteBastion",
		desc = "Defense-Typ: Steinmauer, Burrow und Schockpulse.",
		creatorStore = {
			searchTerms = { "spinning top defense", "heavy metal top", "stone bey" },
			hint = "Creator Store: breiter Ring-Top → modelAssets.meshId setzen",
		},
	},
	{
		id = "SolarDrift",
		name = "Solar Drift",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 170, 40),
		accentColor = Color3.fromRGB(255, 230, 100),
		stats = { Attack = 5, Defense = 6, Speed = 8, Stamina = 10, SpinDecayMult = 0.6 },
		special = "Solar Corona Loop",
		specialId = "SolarCoronaLoop",
		desc = "Stamina-Typ: Sonnenringe und Orbit-Tempest.",
		creatorStore = {
			searchTerms = { "spinning top gold", "sun top bey", "stamina ring top" },
			hint = "Flacher Gold-Ring aus Toolbox → modelAssets.meshId",
		},
	},
	{
		id = "PhantomEdge",
		name = "Phantom Edge",
		beyType = "Balance",
		color = Color3.fromRGB(70, 180, 200),
		accentColor = Color3.fromRGB(140, 240, 255),
		stats = { Attack = 7, Defense = 5, Speed = 7, Stamina = 6 },
		special = "Phantom Mirage Slash",
		specialId = "PhantomMirageSlash",
		desc = "Balance-Typ: Geister-Aura, Dive und Frost-Burst.",
		creatorStore = {
			searchTerms = { "spinning top cyan", "phantom blade top", "ice bey top" },
			hint = "Transparente Klingen-Top → modelAssets.meshId",
		},
	},
	{
		id = "CrystalEdge",
		name = "Crystal Edge",
		beyType = "Attack",
		color = Color3.fromRGB(120, 200, 255),
		accentColor = Color3.fromRGB(200, 240, 255),
		stats = { Attack = 8, Defense = 5, Speed = 7, Stamina = 5 },
		special = "Crystal Shard Barrage",
		specialId = "CrystalShardBarrage",
		desc = "Attack-Typ: Eissplitter-Meteore und Rush.",
		creatorStore = {
			searchTerms = { "crystal spinning top", "ice shard bey", "diamond top" },
			hint = "Kristall-Top aus Creator Store → modelAssets.meshId",
		},
	},
	{
		id = "BlazeCrown",
		name = "Blaze Crown",
		beyType = "Attack",
		color = Color3.fromRGB(255, 95, 30),
		accentColor = Color3.fromRGB(255, 180, 60),
		stats = { Attack = 9, Defense = 4, Speed = 7, Stamina = 5 },
		special = "Blaze Inferno Crown",
		specialId = "BlazeInfernoCrown",
		desc = "Attack-Typ: Flammen-Krone und Inferno-Ringe.",
		creatorStore = {
			searchTerms = { "fire spinning top", "flame bey top", "inferno top" },
			hint = "Feuer-Top aus Toolbox → modelAssets.meshId",
		},
	},
}

return BeyCatalog
