local BeyConfig = {
	MATCH_COUNTDOWN = 3,
	MAX_HP = 100,
	MAX_SPIN = 100,
	MAX_SPECIAL = 100,

	BASE_SPEED = 22,
	CHARGE_SPEED_MULT = 1.4,
	DODGE_SPEED = 40,
	DODGE_DURATION = 0.28,
	SPIN_DECAY = 0.08,

	-- Realistic momentum physics
	ACCEL_FORCE = 90,
	COAST_FRICTION = 24,
	TURN_RATE = 5.2,
	MAX_SPEED_MULT = 1.1,
	WALL_BOUNCE = 0.4,
	WALL_FRICTION = 0.8,
	BOWL_PULL = 16,
	ARENA_RADIUS = 36,
	KNOCKBACK_BASE = 16,
	KNOCKBACK_SCALE = 0.5,
	SPECIAL_RUSH_SPEED = 72,

	HIT_DAMAGE = 9,
	HIT_SPIN_LOSS = 4,
	HIT_SPECIAL_GAIN = 14,
	HIT_COOLDOWN = 0.65,

	SPECIAL_DAMAGE = 35,
	SPECIAL_SPIN_LOSS = 15,
	SPECIAL_DURATION = 0.75,
	SPECIAL_COOLDOWN = 1.8,

	SPECIAL_MOVES = {
		StarfallRush = {
			vfx = "StarfallRush",
			mode = "rush",
			duration = 0.75,
			rushSpeed = 72,
			damage = 35,
			spinLoss = 15,
			color = Color3.fromRGB(120, 200, 255),
		},
		ShellGuard = {
			vfx = "ShellGuard",
			mode = "guard",
			duration = 1.4,
			rushSpeed = 8,
			damage = 14,
			spinLoss = 6,
			damageReduction = 0.5,
			pulseInterval = 0.35,
			pulseRange = 7,
			color = Color3.fromRGB(80, 200, 120),
		},
		ThunderLoop = {
			vfx = "ThunderLoop",
			mode = "orbit",
			duration = 0.9,
			rushSpeed = 58,
			damage = 28,
			spinLoss = 12,
			orbitRadius = 5,
			orbitSpeed = 14,
			color = Color3.fromRGB(255, 220, 80),
		},
		NightFang = {
			vfx = "NightFang",
			mode = "lunge",
			duration = 0.5,
			rushSpeed = 88,
			damage = 42,
			spinLoss = 18,
			color = Color3.fromRGB(160, 80, 240),
		},
		CrimsonRipper = {
			vfx = "CrimsonRipper",
			mode = "zigzag",
			duration = 1.1,
			rushSpeed = 76,
			damage = 38,
			spinLoss = 16,
			zigzagCount = 3,
			color = Color3.fromRGB(230, 60, 50),
		},
		GraniteBastion = {
			vfx = "GraniteBastion",
			mode = "guard",
			duration = 1.6,
			rushSpeed = 6,
			damage = 12,
			spinLoss = 5,
			damageReduction = 0.7,
			pulseInterval = 0.35,
			pulseRange = 9,
			color = Color3.fromRGB(140, 130, 110),
		},
		SolarFlare = {
			vfx = "SolarFlare",
			mode = "orbit",
			duration = 1.0,
			rushSpeed = 52,
			damage = 30,
			spinLoss = 10,
			orbitRadius = 7,
			orbitSpeed = 15,
			color = Color3.fromRGB(255, 190, 50),
		},
		PhantomMirage = {
			vfx = "PhantomMirage",
			mode = "lunge",
			duration = 0.85,
			rushSpeed = 86,
			damage = 40,
			spinLoss = 14,
			cloneCount = 2,
			color = Color3.fromRGB(120, 180, 255),
		},
	},
	STATS_SYNC_INTERVAL = 0.12,

	DUMMY = {
		SPEED = 12,
		ATTACK = 4,
		DEFENSE = 8,
	},

	PLAYER = {
		SPEED = 7,
		ATTACK = 8,
		DEFENSE = 4,
	},

	SELECTION_TIMEOUT = 20,

	SOUNDS = {
		HIT = "rbxassetid://9119723401",
		SPECIAL = "rbxassetid://12222216",
		VICTORY = "rbxassetid://1843532710",
		DEFEAT = "rbxassetid://4960035809",
		SELECT = "rbxassetid://6895079853",
	},
}

return BeyConfig
