local BeyCatalog = {
	{
		id = "NovaStriker",
		name = "Nova Striker",
		beyType = "Attack",
		color = Color3.fromRGB(80, 140, 255),
		accentColor = Color3.fromRGB(120, 210, 255),
		stats = { Attack = 8, Defense = 4, Speed = 7, Stamina = 5 },
		special = "Nova Meteor Shower",
		specialId = "NovaMeteorShower",
		desc = "Attack-Typ: Multi-Hit Meteor-Rush aus der Luft.",
		modelRef = {
			sketchfabId = "6bd1a9f1864a46dba4632307ce6c2660",
			sketchfabUrl = "https://sketchfab.com/models/6bd1a9f1864a46dba4632307ce6c2660",
			referenceName = "Storm Pegasus 105 RF",
			credit = "IcaroAndradeOliveira1",
			studioModelName = "NovaStriker",
		},
	},
	{
		id = "IronShell",
		name = "Iron Shell",
		beyType = "Defense",
		color = Color3.fromRGB(80, 180, 110),
		accentColor = Color3.fromRGB(130, 255, 170),
		stats = { Attack = 4, Defense = 8, Speed = 5, Stamina = 8 },
		special = "Iron Vault Lock",
		specialId = "IronVaultLock",
		desc = "Defense-Typ: Burrow, Schutzmauer und Schockwellen.",
	},
	{
		id = "VoltDash",
		name = "Volt Dash",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 200, 60),
		accentColor = Color3.fromRGB(255, 240, 120),
		stats = { Attack = 6, Defense = 5, Speed = 9, Stamina = 9, SpinDecayMult = 0.65 },
		special = "Volt Sonic Tempest",
		specialId = "VoltSonicTempest",
		desc = "Stamina-Typ: Sonic-Ringe und Orbit-Angriff.",
	},
	{
		id = "ShadowBite",
		name = "Shadow Bite",
		beyType = "Balance",
		color = Color3.fromRGB(140, 80, 220),
		accentColor = Color3.fromRGB(200, 100, 255),
		stats = { Attack = 7, Defense = 6, Speed = 6, Stamina = 6 },
		special = "Shadow Eclipse Fang",
		specialId = "ShadowEclipseFang",
		desc = "Balance-Typ: Dark-Aura, Dive und Venom-Burst.",
	},
	{
		id = "CrimsonFang",
		name = "Crimson Fang",
		beyType = "Attack",
		color = Color3.fromRGB(200, 45, 55),
		accentColor = Color3.fromRGB(255, 90, 70),
		stats = { Attack = 9, Defense = 3, Speed = 8, Stamina = 4 },
		special = "Crimson Ripper Claw",
		specialId = "CrimsonRipperClaw",
		desc = "Attack-Typ: Blutrote Klaue mit Meteor-Rush.",
		creatorStore = {
			searchTerms = { "spinning top", "attack top", "metal bey" },
			notes = "Flat on ground, ~3.5 stud diameter. Paste meshId into modelAssets.",
		},
	},
	{
		id = "GraniteFort",
		name = "Granite Fort",
		beyType = "Defense",
		color = Color3.fromRGB(110, 105, 100),
		accentColor = Color3.fromRGB(160, 150, 140),
		stats = { Attack = 3, Defense = 9, Speed = 4, Stamina = 8 },
		special = "Granite Bulwark",
		specialId = "GraniteBulwark",
		desc = "Defense-Typ: Steinerne Festung mit Schockpulsen.",
		creatorStore = {
			searchTerms = { "heavy top", "defense bey", "stone spinning" },
			notes = "Wide base preferred. Paste meshId into modelAssets.",
		},
	},
	{
		id = "SolarDrift",
		name = "Solar Drift",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 160, 40),
		accentColor = Color3.fromRGB(255, 220, 100),
		stats = { Attack = 5, Defense = 6, Speed = 8, Stamina = 9, SpinDecayMult = 0.6 },
		special = "Solar Flare Orbit",
		specialId = "SolarFlareOrbit",
		desc = "Stamina-Typ: Sonnenringe und Orbit-Angriff.",
		creatorStore = {
			searchTerms = { "golden top", "stamina bey", "flat ring top" },
			notes = "Low profile ring shape works best.",
		},
	},
	{
		id = "PhantomEdge",
		name = "Phantom Edge",
		beyType = "Balance",
		color = Color3.fromRGB(60, 180, 175),
		accentColor = Color3.fromRGB(120, 255, 240),
		stats = { Attack = 7, Defense = 5, Speed = 7, Stamina = 6 },
		special = "Phantom Vanish Strike",
		specialId = "PhantomVanishStrike",
		desc = "Balance-Typ: Geister-Aura, Dive und Burst.",
		creatorStore = {
			searchTerms = { "phantom top", "teal spinning", "balance bey" },
		},
	},
	{
		id = "CrystalEdge",
		name = "Crystal Edge",
		beyType = "Attack",
		color = Color3.fromRGB(140, 200, 255),
		accentColor = Color3.fromRGB(220, 245, 255),
		stats = { Attack = 8, Defense = 5, Speed = 7, Stamina = 5 },
		special = "Crystal Shard Storm",
		specialId = "CrystalShardStorm",
		desc = "Attack-Typ: Eissplitter-Regen aus der Luft.",
		creatorStore = {
			searchTerms = { "crystal top", "ice bey", "sharp blade top" },
		},
	},
	{
		id = "BlazeCrown",
		name = "Blaze Crown",
		beyType = "Balance",
		color = Color3.fromRGB(255, 100, 30),
		accentColor = Color3.fromRGB(255, 180, 60),
		stats = { Attack = 7, Defense = 6, Speed = 6, Stamina = 7 },
		special = "Blaze Inferno Crown",
		specialId = "BlazeInfernoCrown",
		desc = "Balance-Typ: Flammenkrone mit Inferno-Burst.",
		creatorStore = {
			searchTerms = { "fire top", "flame bey", "crown spinning" },
		},
	},
}

return BeyCatalog
