local BeyCatalog = {
	{
		id = "NovaStriker",
		name = "Nova Striker",
		beyType = "Attack",
		color = Color3.fromRGB(80, 140, 255),
		accentColor = Color3.fromRGB(120, 210, 255),
		stats = { Attack = 8, Defense = 4, Speed = 7, Stamina = 5 },
		special = "Nova Meteor Shower",
		specialId = "NovaMeteorShower",
		desc = "Attack-Typ: Multi-Hit Meteor-Rush aus der Luft.",
		modelRef = {
			sketchfabId = "6bd1a9f1864a46dba4632307ce6c2660",
			sketchfabUrl = "https://sketchfab.com/models/6bd1a9f1864a46dba4632307ce6c2660",
			referenceName = "Storm Pegasus 105 RF",
			credit = "IcaroAndradeOliveira1",
			studioModelName = "NovaStriker",
		},
	},
	{
		id = "IronShell",
		name = "Iron Shell",
		beyType = "Defense",
		color = Color3.fromRGB(80, 180, 110),
		accentColor = Color3.fromRGB(130, 255, 170),
		stats = { Attack = 4, Defense = 8, Speed = 5, Stamina = 8 },
		special = "Iron Vault Lock",
		specialId = "IronVaultLock",
		desc = "Defense-Typ: Burrow, Schutzmauer und Schockwellen.",
		modelRef = { studioModelName = "IronShell" },
	},
	{
		id = "VoltDash",
		name = "Volt Dash",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 200, 60),
		accentColor = Color3.fromRGB(255, 240, 120),
		stats = { Attack = 6, Defense = 5, Speed = 9, Stamina = 9, SpinDecayMult = 0.65 },
		special = "Volt Sonic Tempest",
		specialId = "VoltSonicTempest",
		desc = "Stamina-Typ: Sonic-Ringe und Orbit-Angriff.",
		modelRef = { studioModelName = "VoltDash" },
	},
	{
		id = "ShadowBite",
		name = "Shadow Bite",
		beyType = "Balance",
		color = Color3.fromRGB(140, 80, 220),
		accentColor = Color3.fromRGB(200, 100, 255),
		stats = { Attack = 7, Defense = 6, Speed = 6, Stamina = 6 },
		special = "Shadow Eclipse Fang",
		specialId = "ShadowEclipseFang",
		desc = "Balance-Typ: Dark-Aura, Dive und Venom-Burst.",
		modelRef = { studioModelName = "ShadowBite" },
	},
	{
		id = "CrimsonFang",
		name = "Crimson Fang",
		beyType = "Attack",
		color = Color3.fromRGB(200, 45, 55),
		accentColor = Color3.fromRGB(255, 110, 80),
		stats = { Attack = 9, Defense = 3, Speed = 8, Stamina = 5 },
		special = "Crimson Fang Rend",
		specialId = "CrimsonFangRend",
		desc = "Attack-Typ: Scharfe Scherben-Salve.",
		modelRef = { studioModelName = "CrimsonFang" },
	},
	{
		id = "GraniteFort",
		name = "Granite Fort",
		beyType = "Defense",
		color = Color3.fromRGB(110, 105, 95),
		accentColor = Color3.fromRGB(175, 165, 145),
		stats = { Attack = 3, Defense = 9, Speed = 4, Stamina = 7 },
		special = "Granite Bastion",
		specialId = "GraniteBastion",
		desc = "Defense-Typ: Felsenmauer und Erdstoß.",
		modelRef = { studioModelName = "GraniteFort" },
	},
	{
		id = "SolarDrift",
		name = "Solar Drift",
		beyType = "Stamina",
		color = Color3.fromRGB(255, 155, 35),
		accentColor = Color3.fromRGB(255, 225, 95),
		stats = { Attack = 5, Defense = 6, Speed = 8, Stamina = 10, SpinDecayMult = 0.6 },
		special = "Solar Helix",
		specialId = "SolarHelix",
		desc = "Stamina-Typ: Sonnenwind-Spiralen.",
		modelRef = { studioModelName = "SolarDrift" },
	},
	{
		id = "PhantomEdge",
		name = "Phantom Edge",
		beyType = "Balance",
		color = Color3.fromRGB(95, 175, 195),
		accentColor = Color3.fromRGB(175, 235, 255),
		stats = { Attack = 6, Defense = 5, Speed = 7, Stamina = 7 },
		special = "Phantom Phase",
		specialId = "PhantomPhase",
		desc = "Balance-Typ: Geisterstoß und Phasenriss.",
		modelRef = { studioModelName = "PhantomEdge" },
	},
	{
		id = "CrystalEdge",
		name = "Crystal Edge",
		beyType = "Attack",
		color = Color3.fromRGB(90, 215, 250),
		accentColor = Color3.fromRGB(195, 250, 255),
		stats = { Attack = 8, Defense = 5, Speed = 7, Stamina = 5 },
		special = "Crystal Shatter Surge",
		specialId = "CrystalShatterSurge",
		desc = "Attack-Typ: Kristall-Explosion in alle Richtungen.",
		modelRef = { studioModelName = "CrystalEdge" },
	},
	{
		id = "BlazeCrown",
		name = "Blaze Crown",
		beyType = "Attack",
		color = Color3.fromRGB(250, 85, 25),
		accentColor = Color3.fromRGB(255, 175, 55),
		stats = { Attack = 8, Defense = 4, Speed = 8, Stamina = 6 },
		special = "Blaze Crown Spiral",
		specialId = "BlazeCrownSpiral",
		desc = "Attack-Typ: Feuer-Spirale mit Brandschaden.",
		modelRef = { studioModelName = "BlazeCrown" },
	},
}

return BeyCatalog
